substitutions:
  device_name: "tomada-mrl" #nome do MCU
  friendly_name: "Tomada MLR" #nome amigavel do MCU
  device_info: "Tomada MLR GSD-T2 141"
  device_location: "Cozinha" # lugar onde está instalado - HA
  device_extras: "Tomada MLR Gosund T2 141 CUCO Z0 R v1.2 " # descriçao das funçoes extras do MCU
  device_api_key: !secret api_key_gosound-t2
  device_ota_key: !secret ota_key_esp
  device_ip_addr: !secret ip_gosound-t2
  device_addr: "141"

  sp1_current_resistor: "0.00221"
  sp1_voltage_divider: "820"   #"871"
  #############
  # Note: These numbers were found online
  # BW SHP2 Current Resistor: 0.0028
  # BW SHP2 Voltage Devider: 960
  # Gosund SP1 Current Resistor: 0.00221
  # Gosund SP1 Voltage Devider: 871
  # Gosund SP1 Current Resistor ALT: 0.00103
  # Gosund SP1 Voltage Devider ALT: 2160
  #############
  red_led_pin: GPIO13
  blue_led_pin: GPIO1

packages:
  <<: !include_dir_named common
  board: !include boards/esp8285.yaml

#wifi:
#  use_address: 192.168.1.141

sensor:
  # Gosund SP1 Config
  # Power sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${sp1_current_resistor}
    voltage_divider: ${sp1_voltage_divider}
    change_mode_every: 8
    update_interval: 5s
    # Current sensor
    current:
      name: ${friendly_name} Amperes
      unit_of_measurement: A
      accuracy_decimals: 2
    # Voltage sensor
    voltage:
      name: ${friendly_name} Volts
      unit_of_measurement: V
      accuracy_decimals: 0
    # Power sensor
    power:
      id: power
      name: ${friendly_name} Watts
      unit_of_measurement: W
      accuracy_decimals: 0
  # Total daily energy sensor
  - platform: total_daily_energy
    name: ${friendly_name} KWh
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
# Binary sensor for the power button
binary_sensor:
  - platform: gpio
    name: ${friendly_name} Botao
    id: botaoonoff
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: relay
    internal: False

switch:
  # Switch for the relay
  - platform: gpio
    id: relay
    name: ${friendly_name}
    icon: "mdi:washing-machine"
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # esphome state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: ${blue_led_pin}
      inverted: true

light:
  # Power state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a status indicator
status_led:
  pin:
    number: ${red_led_pin}
    inverted: true
    