substitutions:
  device_name: "interruptor" #nome do MCU
  friendly_name: "Interruptor" #nome amigavel do MCU
  device_location: "Sala de estar" # lugar onde está instalado
  device_extras: "Entrada, Cozinha, Corredor, WC-Iluminaçaoo e ventilhação " # descriçao das funçoes extras do MCU
  device_description: ${friendly_name} - ${device_location} - ${device_extras} # descriçao do MCU

<<: !include include/dados.yaml

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  build_path: ./projectos/${friendly_name} - ${device_location}
  platform: ESP8266
  board: d1_mini


# Enable logging 
# DEBUG or null - (Default) - Color: cyan; 
# INFO - errors, warnings and info - Color: green;
# VERBOSE - Like debug, but a few more messages - Color: grey
# WARN - warnings and errors are logged - Color: yellow
logger:
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_interruptor
ota:
  password: !secret ota_password_interruptor

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.126
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: !secret dns1_ip
    dns2: !secret dns2_ip

  ap:
    ssid: "interruptor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
    

binary_sensor:
  - platform: gpio  #Interruptor da Sala 1 entrada GPIO14
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: Botao sala 1
    id: interruptorsalaentrada
    icon: mdi:electric-switch
    internal: False
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
#
  - platform: gpio ##Interruptor da Sala 2 Corredor - GPIO12
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: Botao sala 2
    id: interruptorsalacorredor
    icon: mdi:electric-switch
    internal: False
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
#
  - platform: gpio #Interruptor do WC Corredor - GPIO13
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: Botão WC
    id: interruptorwccorredor
    icon: mdi:electric-switch
    internal: False
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - switch.toggle: iluminacao_wc
    on_release:
      then:
        - switch.toggle: iluminacao_wc
#
  - platform: gpio #Interruptor da Cozinha - GPIO3 RX - HIGH at boot
    pin:
      number: GPIO3
    name: Botao cozinha
    id: interruptornacozinha
    icon: mdi:electric-switch
    internal: False
    filters:
      - invert:
      - delayed_on: 10ms
      - delayed_off: 10ms

############################# GPIO4 SDA (I2C) GPIO5 SCL (I2C)
switch:
  - platform: gpio
    name: Iluminação WC # relé 1
    pin: 
      number: D1
    inverted: True
    icon: mdi:globe-light
    id: iluminacao_wc
#
  - platform: gpio
    name: Ventilação WC # relé 2
    pin: 
      number: D2
    inverted: True
    icon: mdi:fan
    id: ventilador_wc
#########################
###
  - platform: restart
    name: ${friendly_name} Restart
button:
  - platform: safe_mode
    name: ${friendly_name} Restart (Safe Mode)
###
sensor:

#sensor:
  - platform: homeassistant
    name: "Humidade WC HA"
    unit_of_measurement: "°C"
    entity_id: sensor.humidade_wc
    filters:
    internal: False
#################
  - platform: homeassistant
    id: humidity
    entity_id: sensor.humidade_wc
    attribute: humidity
    filters:
    internal: False

# Diagnosticos
  - platform: uptime # Reporta o tempo de actividade online
    name: ${friendly_name} Tempo Online
    icon: mdi:timeline-clock
    filters:
      - lambda: return x / 3600.0;

    unit_of_measurement: "horas"
    accuracy_decimals: 2 

  - platform: wifi_signal # Reporta a força do sinal WiFi em dB
    name: ${friendly_name} Sinal WiFi dB
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy # Reporta a força do sinal WiFi em %
    source_id: wifi_signal_db
    name: ${friendly_name} Sinal WiFi %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
