substitutions:
  device_name: "lampadas-do-quarto" #nome do MCU
  friendly_name: "Luz do quarto" #nome amigavel do MCU
  device_info: "Iluminaçao"
  device_location: "Quarto" # lugar onde está instalado
  device_extras: "2x lampadas - 1x SSR - 1x led Strip - ESP32-D1 Mini" # descriçao das funçoes extras do MCU
  device_api_key: !secret api_key_luz_quarto
  device_ota_key: !secret ota_key_luz_quarto
  device_ip_addr: !secret ip_luz_quarto
  device_addr: "133"

packages:
  <<: !include_dir_named common
  board: !include boards/esp32-d1-mini.yaml
  i2c: !include components/i2c_esp32.yaml

# Pinout:
# GPIO19 - COB - Roxo
# GPIO17 - fita led RGB - Branco
# I2C 
#     - sda: GPIO21 cinza 
#     - scl: GPIO22 laranja


# Iluminaçao lampada branca no tecto do quarto - SSR1 roxo

output:
  - platform: ledc
    pin: GPIO19 # - roxo
    id: led_cob_out
    zero_means_zero: False
    min_power: 0.00
    max_power: 0.99

  - platform: ledc
    pin: GPIO26 # - verde
    id: led_cob_out2
    zero_means_zero: False
    min_power: 0.00
    max_power: 0.99

light:
  - platform: monochromatic
    restore_mode: ALWAYS_OFF
    output: led_cob_out
    name: "Lampada COB"
    id: luz_tecto_1
    icon: mdi:globe-light

  - platform: monochromatic
    restore_mode: ALWAYS_OFF
    output: led_cob_out2
    name: "Lampada Quente"
    id: luz_tecto_2
    icon: mdi:globe-light


# LED Strip - GPIO17 - Branco

  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO16
    num_leds: 35
    name: "Leds do Quarto"
    icon: mdi:led-strip
    id: led_rgb_quarto



#  - platform: esp32_rmt_led_strip
#    rgb_order: GRB
#    pin: 
#      number: GPIO16
#      allow_other_uses: true
#    num_leds: 35
#    rmt_channel: 1
#    chipset: ws2812
#    name: "Leds do Quarto"
#    icon: mdi:led-strip
#    id: led_rgb_quarto

sensor:
  - platform: aht10
    temperature:
      name: "Temperatura do Quarto"
      accuracy_decimals: 1
      filters:
#      - filter_out: 0.0
# Example filters:
#      filters:
#        - offset: 2.0
#        - multiply: 1.2
        - calibrate_linear:
            - 4.0 -> 0.0
            - 24.0 -> 20.0
            - 29.0 -> 25.0

      id: air_temperature
    humidity:
      name: "Humidade do Quarto"
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      id: relative_humidity
    update_interval: 10s
