substitutions:
  device_name: "luz-cozinha" #nome do MCU
  friendly_name: "Lampada" #nome amigavel do MCU
  device_info: "Luz da Cozinha"
  device_location: "Cozinha" # lugar onde está instalado - HA
  device_extras: "Sensor de presença LD2410B ESP32 D1 Mini - 2 lampadas Temperatura e humidade " # descriçao das funçoes extras do MCU
  device_api_key: !secret api_key_luz-cozinha
  device_ota_key: !secret ota_key_luz-cozinha
  device_ip_addr: !secret ip_luz-cozinha
  device_addr: "121"

###  ESPECIFICO PARA SENSOR DE PRESENÇA LD2410 UART
  target_device_1: luz_da_cozinha_1 # id do dispositivo 1 a ser controlado Lampadas ou relés ou outro
  target_device_2: luz_da_cozinha_2 # id do dispositivo 2 a ser controlado Lampadas ou relés ou outro
  target_name: ${device_info}
  tx_pin: GPIO17 # Pin TX  uart Esp8266 ou ESP32 UART0-> tx_pin: GPIO1 - UART2-> tx_pin: GPIO17 - Verde
  rx_pin: GPIO16 # Pin RX  uart Esp8266 ou ESP32 UART0-> rx_pin: GPIO3 - UART2-> rx_pin: GPIO16 - Amarelo
####

packages:
  <<: !include_dir_named common
  ld2410 <<: !include devices/ld2410.yaml
  board: !include boards/esp32-d1-mini.yaml
#  i2c: !include components/i2c_esp32.yaml

# Detector de presença LD2410C usando UART
binary_sensor:
  ##
  - platform: ld2410
    has_target:
      name: "1 Presença ${target_name}"
      id: alvo_detetado
      device_class: occupancy

    has_moving_target:
      name: "3 Alvo movimento ${target_name}"
      id: alvo_movimento
      device_class: moving

    has_still_target:
      name: "2 Alvo fixo ${target_name}"
      id: alvo_fixo
      device_class: occupancy
      on_press:
        then:
          - if:
              condition:
                and:
                  - binary_sensor.is_on: alvo_fixo
                  - binary_sensor.is_on: alvo_detetado
                  #- light.is_off: "${target_2}"
                  #- lambda: |-
                  #    return id(energia_alvo_parado).state > 60;
              then:
                - light.turn_on: "${target_1}"

      on_release:
        then:
          - if:
              condition:
                and:
                  - binary_sensor.is_off: alvo_detetado
                  - binary_sensor.is_off: alvo_fixo
                  #- light.is_off: "${target_2}"
                  #- lambda: |-
                  #    return id(energia_alvo_parado).state < 20;
              then:
                - delay: 2s
                - light.turn_off: "${target_1}"


    out_pin_presence_status:
      name: "Out Pin ${target_name}" # out pin presence status
      id: out_pin_status
      device_class: occupancy


switch:
# GPIO18 luz_da_cozinha_1 SSR1 Azul
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number:  GPIO18
      allow_other_uses: true
      inverted: True
    name: ${device_info} 1 # SSR 1 Vermelho
    internal: True
    icon: mdi:globe-light
    id: iluminacao_1
    device_class: switch
# GPIO19 - luz_da_cozinha_2 SSR2 Roxo
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO19
      allow_other_uses: True
      inverted: True
    name: ${device_info} 2 # SSR 2 Preto
    internal: True
    icon: mdi:globe-light
    id: iluminacao_2
    device_class: switch

light:
  - platform: binary
    name: ${device_info} Auto
    output: light_output_cozinha_1
    restore_mode: ALWAYS_OFF
    internal: False
    id: luz_da_cozinha_1
    icon: mdi:ceiling-light

  - platform: binary
    name: ${device_info} Manual
    output: light_output_cozinha_2
    restore_mode: ALWAYS_OFF
    internal: False
    id: luz_da_cozinha_2
    icon: mdi:ceiling-light
output:
  - id: light_output_cozinha_1
    platform: gpio
    pin:
      number: GPIO18
      allow_other_uses: true
      inverted: True
  - id: light_output_cozinha_2
    platform: gpio
    pin:
      number: GPIO19
      allow_other_uses: true
      inverted: True



sensor:
  - platform: dht
    pin: GPIO23  # 3V3 - Sensor de temperatura e humidade Sonoff Si7021 Cinza
    temperature:
      name: ${device_info} Temperatura
      filters:
        - calibrate_linear:
            - 4.0 -> 0.0
            - 24.0 -> 20.0
            - 29.0 -> 25.0
    humidity:
      name: ${device_info} Humidade
    update_interval: 60s
    model: Si7021

