substitutions:
  device_name: "media-player-cozinha" #nome do MCU
  friendly_name: "Coluna" #nome amigavel do MCU
  device_location: "Cozinha" # lugar onde está instalado
  device_info: "louder Esp32-S3 WROOM-1 N16R8"
  device_extras: "Louder Esp32-S3 N16R8 Media Player Sonocotta" # descriçao das funçoes extras do MCU
  device_api_key: !secret api_key_louder-cozinha
  device_ota_key: !secret ota_key_esp
  device_ip_addr: !secret ip_louder-cozinha
  device_addr: "137"
  pcb_version: "J2"

# Louder Esp32-S3 N16R8 Media Player Cozinha Sonocotta 192.168.1.137
#api_key_louder-cozinha: "YSQ21Mls5xpaDzrJvUo8u8pRwsdlMieZ39FAO+hsfLo="
#ota_key_louder-cozinha: "99166ea1a85515f816a75fea21080a0f"
#ip_louder-cozinha: 192.168.1.137




packages:
  <<: !include_dir_named common
  board: !include boards/louder-esp32-s3-n16r8.yaml
#  i2c: !include components/i2c_louder_esp32_s3.yaml


esphome:
  name_add_mac_suffix: false
  includes:
    - include/louderesp32-s3.h
  platformio_options:
    lib_deps: "Wire"
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
  on_boot:
    priority: 800
    then:
    ## Set a volume limit just to be safe...
    - media_player.volume_set:
        id: media_player_cozinha #louderesp32
        volume: 20%
  libraries:
    - "Wire"
### Optional if you want ethernet (then remove all wifi config) ###
#ethernet:
#  type: W5500
#  clk_pin: GPIO12
#  mosi_pin: GPIO11
#  miso_pin: GPIO13
#  cs_pin: GPIO10
#  interrupt_pin: GPIO6
#  reset_pin: GPIO5

# Enable logging
#logger:
#  level: DEBUG

psram:
  mode: octal
  speed: 80MHz

#switch:
#  - platform: custom
#    lambda: |-
#      auto tas5805 = new TAS5805();
#      App.register_component(tas5805);
#      return {tas5805};
#    switches:
#      name: "Enable Amp Cozinha"

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

media_player:
  - platform: i2s_audio
    name: $friendly_name
    id: media_player_cozinha #louderesp32
    dac_type: external
    i2s_dout_pin: GPIO16
    mode: stereo
