##################################################
substitutions:
  device_name: "shelly1" #nome do MCU
  friendly_name: "Shelly1" #nome amigavel do MCU
  device_location: "Quarto" # lugar onde está instalado
  device_info: "shelly1 Esp01m 8266"
  device_extras: "Interruptores Shelly1 com controlo de energia" # descriçao das funçoes extras do MCU
  device_api_key: !secret api_key_shelly1
  device_ota_key: !secret ota_key_shelly1
  device_ip_addr: !secret ip_shelly1
  device_addr: "130"
  max_temp: "70.0"

packages:
  <<: !include_dir_named common
  board: !include boards/esp01s.yaml
#  i2c: !include components/i2c_esp32.yaml

wifi:
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532
  
switch:
  - platform: gpio
    name: $friendly_name
    pin:
      number: GPIO15
      allow_other_uses: true
    id: shelly_relay
    restore_mode: RESTORE_DEFAULT_OFF
#####
light:
  - platform: binary
    name: Luz do quarto
    output: light_output_quarto
    restore_mode: ALWAYS_OFF
    id: luz_do_quarto
    icon: mdi:bed

output:
  - id: light_output_quarto
    platform: gpio
    pin:
      number: GPIO15
      allow_other_uses: true
#####
#output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true
######
sensor:
  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # not used because it is not available on the 1PM but it is needed to compile
    sel_pin: GPIO14 # not used because it is not available on the 1PM but it is needed to compile
    power:
      name: "$friendly_name potencia"
      unit_of_measurement: W
      id: "shelly1pm_power"
      device_class: power
      #state_class: measurement
      state_class: total_increasing
#      last_reset_type: auto
      accuracy_decimals: 0
      filters:
        # Map from sensor -> measured value
      - calibrate_linear:
          - 0.0 -> 1.0
          - 110.33186 -> 20.62
          - 131.01909 -> 24.32
          - 341.33920 -> 62.08
          - 5561.41553 -> 1000.0
          - 2975.51221 -> 535.7
          - 9612.66309 -> 1720.0
          - 14891.35352 -> 2679.0
        # Make everything below 2W appear as just 0W.
      - lambda: if (x < 2) return 0; else return x;
    update_interval: 10s
  


  - platform: total_daily_energy
    name: "$friendly_name energia diaria"
    power_id: "shelly1pm_power"
    unit_of_measurement: kWh
    state_class: total_increasing
    #state_class: measurement
    device_class: energy
#    last_reset_type: auto
    filters:
      - multiply: 0.001

  
  - platform: ntc
    sensor: temp_resistance_reading
    name: "$friendly_name temperatura interna"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${friendly_name} ${device_info} está em sobre aquecimento."
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # debouncing
    name: "Switch ${friendly_name}"
    on_state:
      then:
        - light.toggle: luz_do_quarto
    internal: true
    id: switchid
    icon: mdi:bed
