substitutions:
  device_name: "termoacumulador" #nome do MCU
  friendly_name: "Termoacumulador" #nome amigavel do MCU
  device_location: "Cozinha" # lugar onde está instalado
  device_extras: "Controlo de temperatura" # descriçao das funçoes extras do MCU
  device_description: ${friendly_name} - ${device_location} - ${device_extras} # descriçao do MCU
  update_interval_wifi: "120s"
  name: ${friendly_name}
  update_interval_s: "10s"

<<: !include include/dados.yaml

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  build_path: ./projectos/${friendly_name} - ${device_location}
  platform: ESP8266
  board: d1_mini

#######################
  on_boot:
    - delay: 10s
    - climate.control:
        id: this_thermostat
        mode: HEAT_COOL
    - climate.control:
        id: this_thermostat
        target_temperature_low: 65.0 
        target_temperature_high: 70.0
##########################
# Enable logging 
# DEBUG or null - (Default) - Color: cyan; 
# INFO - errors, warnings and info - Color: green;
# VERBOSE - Like debug, but a few more messages - Color: grey
# WARN - warnings and errors are logged - Color: yellow
logger:
  level: info

api:
  encryption:
    key: !secret api_key_termoacumulador

ota:
  password: !secret ota_password_termoacumulador

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.116
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: !secret dns1_ip
    dns2: !secret dns2_ip

  ap:
    ssid: "${device_name}"
    password: !secret wifi_ap_password 

captive_portal:
time:
  - platform: homeassistant
    id: esptime
    
i2c:
  - id: bus_a
    sda: D1 # GPIO5 
    scl: D2 # GPIO4
    scan: False

dallas:
  - pin: D5 # GPIO14
    update_interval: ${update_interval_s}
  
sensor:
  - platform: uptime
    name: ${friendly_name} - Tempo Online
    icon: mdi:timeline-clock
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "horas"
    accuracy_decimals: 2 
  - platform: wifi_signal
    name: ${friendly_name} - Sinal WiFi dB
    id: wifi_signal_db
    update_interval: ${update_interval_wifi}
  - platform: copy
    source_id: wifi_signal_db
    name: ${friendly_name} - Sinal WiFi %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"

# Dallas DS18B20 sensor:
  - platform: dallas
    address: 0x993c3d0457dc2128
    name: "${friendly_name}: Temperatura da agua"
    device_class: "temperature"
    state_class: "measurement"
    id: temperatura_agua
    unit_of_measurement: "°C"
    icon: "mdi:water-thermometer"
    accuracy_decimals: 2
    filters:
        - heartbeat: 5s
#################################################
climate:
  - platform: thermostat
    name: $name
    id: this_thermostat
    visual:
      min_temperature: 20
      max_temperature: 80
    sensor: temperatura_agua



    default_preset: Home  
    preset:
      - name: Home
        default_target_temperature_low: 65.0  
        default_target_temperature_high: 70.0
  
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              
    min_heating_run_time: 1s              
    min_idle_time: 1s

    cool_action:
      - switch.turn_off: termoacumulador_rele

    heat_action:
      - switch.turn_on: termoacumulador_rele

    idle_action:
      - switch.turn_off: termoacumulador_rele

switch:
  - platform: gpio
    name: ${friendly_name} - rele
    pin: D6 #GPIO12
    id: termoacumulador_rele
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: restart
    name: "${friendly_name}: Restart"
button:
  - platform: safe_mode
    name: "${friendly_name}: Restart (Safe Mode)"

