substitutions:
  device_name: "ventoinha-da-sala" #nome do MCU
  friendly_name: "Ventoinha" #nome amigavel do MCU
  device_location: "Sala de estar" # lugar onde está instalado
  device_extras: "com 3 velocidades" # descriçao das funçoes extras do MCU
  device_description: ${friendly_name} - ${device_location} - ${device_extras} # descriçao do MCU no ESPHome

<<: !include include/dados.yaml

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  build_path: ./projectos/${friendly_name} - ${device_location}
  platform: ESP8266
  board: d1_mini

# Enable logging 
# DEBUG or null - (Default) - Color: cyan; 
# INFO - errors, warnings and info - Color: green;
# VERBOSE - Like debug, but a few more messages - Color: grey
# WARN - warnings and errors are logged - Color: yellow
logger:
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_ventuinha-da-sala

ota:
  password: !secret ota_password_ventuinha-da-sala

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.110
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: !secret dns1_ip
    dns2: !secret dns2_ip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid_ventuinha-da-sala
    password: !secret wifi_ap_password

captive_portal:


binary_sensor:
  - platform: gpio # Configuraçao do botao fisico
    id: push_button
    name: ${friendly_name} - ${device_location} Botão
    pin:
      number: D2
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
        - ON for 1s to 3s
        - OFF for at least 0.2s
        then:
          - logger.log: "Desligar"
          - switch.turn_off: velocidade1
          - switch.turn_off: velocidade2
          - switch.turn_off: velocidade3

      - timing:
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          - logger.log: "1 toque"
          - switch.turn_on: velocidade1

      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          - logger.log: "2 toques"
          - switch.turn_on: velocidade2

      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          - logger.log: "3 toques"
          - switch.turn_on: velocidade3
          
switch: # Configuraçao do motor com 3 velocidades: Minima; Média e Máxima
  - platform: gpio
    name: ${friendly_name} - ${device_location} Mínima
    pin: 
      number: D5
    inverted: True
    icon: mdi:fan-speed-1
    id: velocidade1
    interlock: &interlock_group [velocidade1, velocidade2, velocidade3]
    interlock_wait_time: 300ms
            
  - platform: gpio
    name: ${friendly_name} - ${device_location} Média
    pin: 
      number: D6
    inverted: True
    icon: mdi:fan-speed-2
    id: velocidade2
    interlock: *interlock_group
    interlock_wait_time: 300ms
            
  - platform: gpio
    name: ${friendly_name} - ${device_location} Máxima
    pin: 
      number: D7
    inverted: True
    icon: mdi:fan-speed-3
    id: velocidade3
    interlock: *interlock_group
    interlock_wait_time: 300ms
    
sensor:
# Diagnosticos
  - platform: uptime # Reporta o tempo de actividade online
    name: ${friendly_name} - ${device_location} Tempo Online
    icon: mdi:timeline-clock
    filters:
      - lambda: return x / 3600.0;

    unit_of_measurement: "horas"
    accuracy_decimals: 2 

  - platform: wifi_signal # Reporta a força do sinal WiFi em dB
    name: ${friendly_name} - ${device_location} Sinal WiFi dB
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy # Reporta a força do sinal WiFi em %
    source_id: wifi_signal_db
    name: ${friendly_name} - ${device_location} Sinal WiFi %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
