# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
# some_password: welcome

# Wi-Fi
# Alterar estes dados conforme rede wifi
wifi_ssid: "NOME_DA_REDE_WIFI"
wifi_password: "PASSWORD_DA_REDE_WIFI"
wifi_gateway: 192.168.1.1
wifi_subnet: 255.255.255.0
dns1_ip: 8.8.8.8 # servidor primário de nomes da google: traduz o nome para o respectivo IP
dns2_ip: 8.8.4.4 # servidor secundário de nomes da google:
##############

# Access Point Password
wifi_ap_password: "AP_PASSWORD" # password para ligar ao Access point que é criado no caso do equipamento náo aceder ao WI-FI
# Over The Air Password  para actualizar o equipamento atrav+es do WI-FI
ota_password_esp: "OTA_PASSWORD"
##############

# Sonoff TH16 Candeeiro do escritorio esta chave é gerado quando ligamos o equipamento pela primeiro vez no ESPHOME
# é utilizada para se identificar no Home assistant. Aqui é apenas um exemplo.
api_key_candeiro: "OyCIPNZpLnDryHAaNR9hRGgsnJLtKHn0iLTG5tzYlBU="


