---
# Version Text Sensor
#
# The version text sensor platform exposes the ESPHome version the firmware was
# compiled against as a text sensor.
#
# https://esphome.io/components/text_sensor/version.html
#
#platform: version
##id: text_sensor_version
#id: versao_esphome
#name: "Versao"
#hide_timestamp: true

# Example configuration entry
#text_sensor:
- platform: version
  name: "ESPHome Version"
  id: "versao_esphome"
  hide_timestamp: true
