# In device_base.yaml
#esphome:
#  name: $device_name
# ...

sensor:
  - <<: !include common_sensor.yaml
#  - <<: !include cinclude/wifi_signal.config.yaml
#binary_sensor:
#  - <<: !include include/binary_sensor/connection_status.config.yaml

#switch:
#  - <<: !include include/switch/restart_switch.config.yaml
